/**
 * Import puzzles from Lichess puzzle database CSV into Supabase.
 *
 * Usage:
 *   1. Download: https://database.lichess.org/#puzzles → decompress to lichess_db_puzzle.csv
 *   2. npx tsx scripts/seed-puzzles-from-csv.ts lichess_db_puzzle.csv
 *   3. supabase db push  (to apply the generated migration)
 *
 * CSV columns:
 *   PuzzleId,FEN,Moves,Rating,RatingDeviation,Popularity,NbPlays,Themes,GameUrl,OpeningTags
 */

import * as fs from 'fs'
import * as readline from 'readline'
import * as path from 'path'

const THEMES_MAP: Record<string, string[]> = {
  fork:           ['fork'],
  pin:            ['pin'],
  discovered:     ['discoveredAttack', 'doubleCheck'],
  attraction:     ['attraction', 'deflection'],
  'remove-defender': ['removeDefender', 'overloading'],
  skewer:         ['skewer', 'xRayAttack'],
  trapped:        ['trappedPiece'],
  mate:           ['mateIn1', 'mateIn2', 'mateIn3', 'smotheredMate', 'backRankMate'],
  'forced-draws': ['perpetualCheck', 'stalemate'],
  zwischenzug:    ['zwischenzug', 'interference'],
  sacrifice:      ['sacrifice'],
  subscribers:    ['clearance', 'quietMove', 'zugzwang', 'coercion'],
  hybrid:         ['middlegame', 'endgame', 'exposedKing'],
  'mixed-bonus':  ['crushing', 'equality', 'advantage'],
}

const TARGET_PER_THEME = 150

type PuzzleRow = {
  id: string
  fen: string
  moves: string
  rating: number
  themes: string[]
  gameUrl: string
  nbPlays: number
}

async function main() {
  const csvPath = process.argv[2]
  if (!csvPath) {
    console.error('Usage: npx tsx scripts/seed-puzzles-from-csv.ts <path-to-csv>')
    process.exit(1)
  }

  if (!fs.existsSync(csvPath)) {
    console.error(`File not found: ${csvPath}`)
    process.exit(1)
  }

  // Build reverse index: lichess theme → our category id
  const themeToCategory: Record<string, string[]> = {}
  for (const [catId, lichessThemes] of Object.entries(THEMES_MAP)) {
    for (const t of lichessThemes) {
      if (!themeToCategory[t]) themeToCategory[t] = []
      themeToCategory[t].push(catId)
    }
  }

  // Collect puzzles per category (top by popularity)
  const buckets: Record<string, PuzzleRow[]> = {}
  for (const catId of Object.keys(THEMES_MAP)) buckets[catId] = []

  const rl = readline.createInterface({ input: fs.createReadStream(csvPath), crlfDelay: Infinity })
  let lineNo = 0

  for await (const line of rl) {
    lineNo++
    if (lineNo === 1) continue // header

    const parts = line.split(',')
    if (parts.length < 9) continue

    const [puzzleId, fen, moves, ratingStr,, , nbPlaysStr, themesStr, gameUrl] = parts
    const themes = themesStr ? themesStr.trim().split(' ') : []
    const nbPlays = parseInt(nbPlaysStr ?? '0', 10)
    const rating = parseInt(ratingStr ?? '0', 10)

    for (const theme of themes) {
      const cats = themeToCategory[theme]
      if (!cats) continue
      for (const catId of cats) {
        if (buckets[catId].length < TARGET_PER_THEME * 3) {
          buckets[catId].push({ id: puzzleId, fen, moves, rating, themes, gameUrl: gameUrl?.trim() ?? '', nbPlays })
        }
      }
    }

    // Stop early if all buckets are full enough
    const allFull = Object.values(buckets).every(b => b.length >= TARGET_PER_THEME * 3)
    if (allFull) break
  }

  // Sort each bucket by popularity and take top TARGET_PER_THEME
  const selected: PuzzleRow[] = []
  const seen = new Set<string>()
  for (const [, rows] of Object.entries(buckets)) {
    const top = rows.sort((a, b) => b.nbPlays - a.nbPlays).slice(0, TARGET_PER_THEME)
    for (const r of top) {
      if (!seen.has(r.id)) {
        seen.add(r.id)
        selected.push(r)
      }
    }
  }

  // Generate SQL
  const outPath = path.join(
    path.dirname(csvPath),
    '..', '..', 'supabase', 'migrations', '009_puzzle_bulk.sql',
  )
  const absOut = path.resolve(outPath)

  const lines: string[] = [
    '-- Auto-generated by scripts/seed-puzzles-from-csv.ts',
    `-- Source: Lichess puzzle database (${selected.length} puzzles, ${TARGET_PER_THEME}/theme)`,
    '',
    'INSERT INTO public.puzzles (id, fen, moves, rating, themes, game_url) VALUES',
  ]

  selected.forEach((p, i) => {
    const themes = `ARRAY[${p.themes.map(t => `'${t}'`).join(',')}]`
    const gameUrl = p.gameUrl ? `'${p.gameUrl}'` : 'null'
    const fen = p.fen.replace(/'/g, "''")
    const moves = p.moves.replace(/'/g, "''")
    const comma = i < selected.length - 1 ? ',' : ''
    lines.push(`('${p.id}','${fen}','${moves}',${p.rating},${themes},${gameUrl})${comma}`)
  })

  lines.push('ON CONFLICT (id) DO NOTHING;')

  fs.writeFileSync(absOut, lines.join('\n'), 'utf8')
  console.log(`✓ Generated ${absOut}`)
  console.log(`  Total puzzles: ${selected.length}`)
  for (const [catId, rows] of Object.entries(buckets)) {
    console.log(`  ${catId}: ${Math.min(rows.length, TARGET_PER_THEME)} puzzles`)
  }
  console.log('\nNext step: supabase db push')
}

main().catch(e => { console.error(e); process.exit(1) })
